[위제현] 로또 1단계 구현완료
JNU-econovation/java-study-lotto pull request #14
Opened 2018-10-31 08:59 UTC by wijehyeon

2018-10-31 09:32 UTC, hyukjin-lee requested changes
RacingCar 할때 했던 것들을 많이 까먹으신 듯 한 느낌을 받았습니다 고생하셨어요 👍

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/LottoMachine.java
> +    int Lottos[][] = null;
static final(상수)
클래스 변수
인스턴스 변수
생성자
get set함수
일반 함수

순서가 기본입니다

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/Result.java
> +    public int winningMoney;
static final(상수)
클래스 변수
인스턴스 변수
생성자
get set함수
일반 함수

순서가 기본입니다

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/View/InputView.java
> +    }
함수들 static으로 사용하는게 나을 것 같은데

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/View/ResultView.java
> +        System.out.format("%2.1f", result.calculateEarningRate() * 100);
100개까지 일치하는 경우가 있어도 이렇게 할건가?

2018-10-31 09:32 UTC, hyukjin-lee commented on src/test/java/LottoTest.java
> +public class LottoTest {
단위 테스트는 각 클래스에서 테스트할 수 있는 모든 함수들을 테스트하는 것 입니다. 한 클래스에 다 때려박기 비추천. 나중에 찾기도 힘듭니다

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Utils/Splitor.java
> +public class Splitor {
따로 클래스화해서 util로 분류한 것 굿 👍

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Utils/Splitor.java
> +    public int[] splitStringToIntegerArray(String inputString) {
클래스 이름이 이미 splitor니까 stringToIntegerArray 로 함수이름을 바꾸면 중복이 덜할듯

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Utils/SearchElement.java
> +    public static boolean searchIntegerElement(int[] arr, int targetValue) {
boolean 함수는 보통 is로 시작합니다. 이렇게 이름을 지을 수 없다면 이 함수의 역할이 뭔가 잘못되었거나 두가지 일을 수행하고 있다는 뜻

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Utils/Print.java
> +    }
Lotto라는 클래스를 만들고 거기에 toString 함수를 오버라이딩해서 사용하면 이런 불필요한 클래스는 생길 일이 없을 것 같습니다

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/Result.java
> +    public void ifThereTarget(SearchElement observer, int index, int j) {
함수이름이 매우 이상하네요

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/Result.java
> +    static final int NUMBEROFLOTTOELEMENT = 6;
이런 경우에는 _로 띄어쓰기 구분합니다

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/Result.java
> +    Splitor splitor = new Splitor();
Util 클래스는 Static 함수로 보통 구현해서 이런 쓸데없는 객체 선언 안하는걸 저는 추천하네요

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/LottoStore.java
> +        System.out.println(numberOfBought + "개를 구매했습니다.");
model 영역에서 출력...?

2018-10-31 09:32 UTC, hyukjin-lee commented on src/main/java/Model/LottoMachine.java
> +            Print.printIntegerArray(Lottos[i]);
model 영역에서 출력을 호출하지말고 출력하는 역할을 하는 View에다가 데이터를 담아서 출력해야합니다. 이렇게하면 model 영역에 출력영역까지 의존하게 돼서 레이어간에 서로 의존도가 높아집니다

2018-11-12 05:19 UTC, hyukjin-lee approved these changes

2018-11-12 05:27 UTC, hyukjin-lee approved these changes
일단 머지하긴 하는데 코드 리팩토링할 곳이 많이 보입니다. 요구사항과 공부한걸 의식적으로 적용하려는 모습이 전혀 보이지 않고 그냥 컨벤션이랑 MVC만 지키면서 마음대로 코딩하는거 같네요. step2에서는 분발하셨으면 좋겠습니다.

2018-11-12 05:27 UTC, hyukjin-lee commented on src/main/java/model/LottoMachine.java
> +    public int lottos[][] = null;
왜 변수가 public이고 static final과 List는 default 로 하셨죠?

2018-11-12 05:27 UTC, hyukjin-lee commented on src/main/java/model/LottoMachine.java
> +    public int lottos[][] = null;
LottoMachine 이라는 개념이 왜 LottoNumber를 가지고 있어야 되는지 모르겠습니다. 그리고 lottos가 왜 이차원 배열이죠?

2018-11-12 05:27 UTC, hyukjin-lee commented on src/main/java/model/LottoStore.java
> +    public int numberOfBought;
이걸 왜 public으로 선언했는지 궁금합니다. 그리고 굳이 클래스가 가지고 있어야하는 변수인지 이유가 궁금합니다

2018-11-12 05:27 UTC, hyukjin-lee commented on src/main/java/model/Result.java
> +    public int winningMoney;
그냥 여태 배운거 다 무시하는 코드인거 같은데..?

2018-11-12 05:27 UTC, hyukjin-lee commented on src/test/java/LottoTest.java
> +    }
테스트에 관해서 제가 슬랙에 멘트를 남겼었는데 하나도 반영이 안된 느낌이네요

2018-11-12 07:11 UTC, wijehyeon commented on src/main/java/model/LottoMachine.java
> +    public int lottos[][] = null;
천원 넣으면 한줄나오듯 입력한 개수만큼 한줄 한줄 나와야하니 이차원배열썼습니다.

2018-11-12 07:13 UTC, wijehyeon commented on src/main/java/model/LottoStore.java
> +    public int numberOfBought;
로또가게에서 얼만큼 사는지 알아야 기계에 입력하는 시스템으로 했거든요  이 값을 기계가 알아야해서 public으로 했었구요

2018-11-12 07:13 UTC, wijehyeon commented on src/main/java/model/Result.java
> +    public int winningMoney;
어느부분이 그렇단건지 자세히설명해주세요

2018-11-12 07:14 UTC, wijehyeon commented on src/test/java/LottoTest.java
> +    }
테스트는 고쳐서 다시커밋하겠습니다

2018-11-12 07:16 UTC, hyukjin-lee commented on src/main/java/model/LottoMachine.java
> +    public int lottos[][] = null;
Lotto 객체를 만들어서 List<Lotto> Lottos 로 쓰는게 더 낫지 않을까요? 아무것도 모르는 사람이 코드를 봤을 때는 lottos(로또들)가 왠지 lotto 여러개를 가지고 있을 듯한 이름인데, 실상 자료형을 보면 int형 2차원 배열이어서 한번에 이해하기가 힘들 것 같습니다. List<Lotto> 로 사용하면 lottoNumbers도 필요없어 보입니다

2018-11-12 07:24 UTC, hyukjin-lee commented on src/main/java/model/LottoStore.java
> +    public int numberOfBought;
클래스의 변수는 특별한 일 아니면 private으로 선언합니다. 이유는 스스로 찾아보시고 제가 보기엔 자바 기본기랑 객체지향 개념이 제대로 잡히지 않아서 여태까지 배운걸 자기 방식대로 흡수해버린 것 같습니다. 그리고 클래스의 필드 변수들로는 꼭 필요한 개념들만 들어가야 된다고 말했었습니다. 하나의 변수로부터 파생될 수 있는 것들을 인스턴스 변수로 선언하는 것을 지양해야하고, 해당 클래스가 계속 들고있어야하는 개념적인 변수가 아니라면 굳이 들고있지 않아도 함수에서 입력과 출력으로만으로도 충분히 구현할 수 있습니다.

2018-11-12 07:31 UTC, hyukjin-lee requested changes

2018-11-12 07:31 UTC, hyukjin-lee commented on src/main/java/model/Result.java
> +    public int winningMoney;
model인 클래스 Result의 모든 변수가 왜 public이고, 변수들이 왜이렇게 많고, View가 왜 model의 필드로 존재하는지. 그동안 스터디 하면서 말해왔던 것들 하나하나가 다 무의미해진거 같습니다.

2018-11-12 07:31 UTC, hyukjin-lee commented on src/main/java/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
접근 제어자를 자꾸 안붙여주는 이유

2018-11-12 07:31 UTC, hyukjin-lee commented on src/main/java/model/Result.java
> +    public int winningMoney;
그리고 배열보다는 컬렉션을 주로 사용하길 권장합니다

2018-11-12 07:31 UTC, hyukjin-lee commented on src/main/java/model/Result.java
> +    }
도메인에서 왜 출력하는 함수를 가지고 있죠?

2018-11-12 07:31 UTC, hyukjin-lee commented on src/test/java/LottoTest.java
> +    }
각 클래스 별/ 함수 별로 단위테스트를 작성해보세요

2018-11-12 07:31 UTC, hyukjin-lee commented on src/main/java/view/ResultView.java
> +    Result result;
View에서 왜 model을 가지고 있습니까?

2018-11-12 07:31 UTC, hyukjin-lee commented on src/main/java/view/ResultView.java
> +            System.out.println(i + "개 일치 (" + result.WINNING_MONEY[i] + "원)" + result.rankList[i]);
클래스의 변수를 이렇게 직접접근해서 갖다 써도 되나요? 이렇게 짜면 왜 저희는 DTO 개념을 공부했고 MVC를 공부했을까요?

2018-11-12 07:38 UTC, hyukjin-lee reviewed
저번 피드백때 제대로 리뷰를 해줬어야 했는데, 제가 할 것도 많은데다가 고칠 부분이 너무 많아서 당시에 너무 스트레스 받은 나머지 그냥 대충 짧게 할 수 있는 피드백들만 남겼습니다. 저도 이 점은 죄송한데 오늘 코드를 보니까 그동안 저희가 해왔던 것들이 다 날아간 느낌이 들어서 강한 피드백들 남깁니다.

2018-11-13 05:19 UTC, esp2ar0 commented on src/main/java/model/LottoMachine.java
> +    public int lottos[][] = null;
상수는 대문자라 단어구분이 안되니 _로 구분하는게 좋아보입니다

2018-11-14 10:24 UTC, merged

2018-11-14 10:54 UTC, Bellroute commented on src/main/java/Main.java
> +        ResultView resultView = new ResultView();
View클래스를 static으로 구현하면 객체를 생성하는 코드 없이 사용가능할 것 같습니다.

2018-11-14 11:10 UTC, esp2ar0 commented on src/main/java/dto/ResultDTO.java
> +        return winningNumbers;
제네릭을 써주는게 좋아보여요

2018-11-14 11:13 UTC, esp2ar0 commented on src/main/java/model/Result.java
> +        if (lotto.getLottoNumbers().contains(index))
is~~ 메소드 네이밍은 주로 boolean값을 리턴할 때 사용합니다

2018-11-14 11:14 UTC, Bellroute commented on src/main/java/view/ResultView.java
> +    public String inputWinningNumbers() {
입력받는 메소드니까 InputView로 옮기는게 좋을 것 같습니다

2018-11-14 14:44 UTC, huhsay commented on src/main/java/Model/LottoMachine.java
> +    public LottoMachine() {
하는 일이 없다면 안써도 되지 않나요?

2018-11-14 14:44 UTC, huhsay commented on src/main/java/Model/LottoMachine.java
> +
문단은 개인이 판단하기에 의미있다고 생각하는 걸로 나누면 된다고 합니다

2018-11-14 14:44 UTC, huhsay commented on src/main/java/Main.java
> +        InputView inputView = new InputView();
ui는 static으로 구성해서 객체를 안만들어도 되게 해야합니다

2018-11-14 14:44 UTC, huhsay commented on src/main/java/Main.java
> +        Result result = new Result(resultView.inputWinningNumbers(), lottoMachine);
lottoMachine 객체를 넘기는게 아니라 lottoMachineDTO를 넘겨야 합니다.

2018-11-14 14:44 UTC, huhsay commented on src/main/java/model/Result.java
> +    private int matchingCounts[] = new int[7];
7 하드 코딩

2018-11-14 14:44 UTC, huhsay commented on src/main/java/model/LottoMachine.java
> +    public LottoMachine() {
필요 없는 생성자 인것 같습니다.  컴파일러가 알아서 해줍니다.

2018-11-14 14:44 UTC, huhsay commented on src/main/java/view/InputView.java
> +    public int purchaseLotto() {
static 사용하기