[김종근] Lotto 미션 1단계 구현완료
JNU-econovation/java-study-lotto pull request #15
Opened 2018-10-31 09:25 UTC by Bellroute

<model>
Lotto : 로또 한 줄에 대한 객체
LottoList : 다 수의 로또를 리스트로 받는 객체
LottoMaker : 로또를 생성하는 class
Spliter : 당첨 번호String을 분리시켜 int배열로 변환하는 class
WinningChecker : LottoList를 당첨번호와 비교하는 class
<dto>
LottoListDTO : LottoList에 대한 DTO
WinningCheckerDTO : 갯수별 당첨 로또 List를 전달하는 DTO

LottoApplication에서 실행

2018-10-31 10:51 UTC, hyukjin-lee commented
이정도 구현이면 본인이 뭘 잘못 구현했는지 알 것 같네요 다시 기운차려서 리팩토링 해봅시다 따로 코멘트는 안할게요

2018-11-03 15:28 UTC, hyukjin-lee requested changes
구현은 매우 잘했는데 테스트가 많이 부실합니다. 구현한 클래스에서 테스트할 수 있는 모든 함수를 테스트해주세요.

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/LottoApplication.java
> +        OutputView.getPurchaseResult(lottoList);
객체 이름은 lottolistDTO로 하는게 더 좋은 것 같습니다

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/LottoApplication.java
> +    private static WinningChecker lottoChecker = new WinningChecker();
winnningChecker가 나은듯 합니다

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/model/Converter.java
> +public class Converter {
이런 성격의 클래스는 util 패키지에 따로 분류하는게 좋습니다. model이라고 하기가 애매하거든요. 이름도 StringConverter가 나을듯

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/model/Lotto.java
> +    private int[] lottoNumbers;
웬만하면 컬렉션을 주로 사용합시다

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/model/LottoMaker.java
> +        return sortedNumbers;
리턴값을 List로 해서 List<> sortedNumbers 로 만들어주고 sortedNumbers.addAll(numbers); 한방이면 for문도 필요없을듯. 이 작업하면서 자바의 깊은 복사 얕은 복사 공부도 추가적으로 해보시면 좋을 것 같습니다

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/model/LottoMaker.java
> +    private static List makeNumbersInRange() {
?? 이 클래스 함수들 왜 다 static이죠?

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/LottoApplication.java
> +    private static WinningChecker lottoChecker = new WinningChecker();
그리고 왜 메인 바깥으로 꺼내서 구현했는지 궁금

2018-11-03 15:28 UTC, hyukjin-lee commented on src/main/java/model/WinningChecker.java
> +    private static List convertArrayToArrayList(int[] numbers) {
여기 클래스에도 왜 static이 범벅되었는지?

2018-11-06 12:36 UTC, Bellroute commented on src/main/java/LottoApplication.java
> +    private static WinningChecker lottoChecker = new WinningChecker();
어플리케이션 실행되면 같이 바로 실행되어야한다고 생각해서 꺼냈습니다

2018-11-06 13:10 UTC, Bellroute commented on src/main/java/model/Lotto.java
> +    private int[] lottoNumbers;
크기가 정해져 있어 바뀌면 안된다고 생각해서 배열썼는데 이런 경우에도 컬렉션을 써야하나요?

2018-11-08 15:32 UTC, hyukjin-lee approved these changes
와우.. 코드보고 감동 먹었습니다. 스터디에서 가장 큰 성장을 하셨네요. 진심으로 리스펙합니다. 지금 코드도 괜찮지만 좀 더 나은 코드가 있을지 스스로 다음주까지 고민하면서 고쳐보세요. 좀 더 추상화 단계를 높인 설계를 해보셔도 좋구요. 예를 들어서 저번에 말씀드린 Stream을 적극 활용하기, LottoNumber까지 클래스로 감싸기 등등이 있을 것 같습니다. 더 쩌는 코드 기대하겠습니다

2018-11-08 15:32 UTC, hyukjin-lee commented on src/main/java/dto/LottoListDTO.java
> +
불필요한 공백

2018-11-08 15:32 UTC, hyukjin-lee commented on src/main/java/LottoApplication.java
> +        OutputView.getPurchaseResult(lottoListDTO);
깔끔하게 lottoMaker.makeLottoList(money).toLottoListDTO(); 를 getpurchase 매개변수로 넣으면 어떨까? 별론가?

2018-11-08 15:32 UTC, hyukjin-lee commented on src/main/java/model/LottoList.java
> +
불필요한 공백

2018-11-08 15:32 UTC, hyukjin-lee commented on src/main/java/model/WinningChecker.java
> +
불필요한 공백

2018-11-09 05:44 UTC, merged

2018-11-14 10:27 UTC, esp2ar0 commented on src/main/java/model/LottoMaker.java
> +
List에 제네릭이 빠졌네요

2018-11-14 10:28 UTC, esp2ar0 commented on src/main/java/model/LottoMaker.java
> +            numbers.add(i);
BOYND_NUMBER를 46으로 해서< 하는것보단
45로 해서 <= 하는게 의미상 더 좋지 않을까요
번호는 45까지니까.
그리고 1은 하드코딩 돼 있네요

2018-11-14 10:29 UTC, esp2ar0 commented on src/main/java/model/LottoMaker.java
> +            lottoList.addLottoToList(makeLotto());
money / 1000 하드코딩

2018-11-14 10:32 UTC, esp2ar0 commented on src/main/java/model/LottoMaker.java
> +            lottoList.addLottoToList(makeLotto());
LotoMaker에서 로또를 만들고, LottoList의 멤버변수에 추가해주기위해 addLottoToList 메소드를 만들어 사용한 것 맞나요?
이렇게 하기 보단 LottoList 내부에서 LotoMaker를 사용해 만들고 add메소드 따로 만들 필요 없이 기본 List의 add를 사용해주면 좋지 않을까요?

2018-11-14 10:34 UTC, esp2ar0 commented on src/main/java/model/LottoList.java
> +
멤버변수 객체의 생성이나 상수를 제외한 변수에 값 할당은 보통 생성자에서 해줍니다.
멤버변수로는 선언만 해주는게 좋아요

2018-11-14 10:44 UTC, sangeuni commented on src/main/java/view/OutputView.java
> +
따로 toString() 만들지 않고 System.out.println(lotto.getLotto().get(i).getLottoNumber()); 이렇게 바꿔도 됩니당

2018-11-14 10:50 UTC, esp2ar0 commented on src/main/java/view/OutputView.java
> +        StringBuilder message = new StringBuilder();
ranking이면 1등 2등 인거같은데 실제 가지고 있는 값은 몇개 일치하는지네요. 이름이 잘못 된 것 같습니다.

또한 몇개 일치하고 그 당첨 금액이 얼마인가는 매개변수로 전달해주지 않아도
WinningInfo.FIRST.get메소드 요런식으로 해서 가져올 수 있습니다. ( 이넘 활용 )

2018-11-14 10:53 UTC, esp2ar0 commented on src/main/java/model/WinningInfo.java
> +    }
enum에서 get을 해서 가져올 때는 몇번째 값을 가져올 지 지정하는 것이 아닙니다.
WinningInfo라는 enum 객체를 생성해서 값을 할당합니다. 예를 들어 FIFTH를 할당 합시다.
그럼 해당 객체에서 get을 해오면 FIFTH에 관한 정보들을 얻는것입니다.
enum 객체가 FIRST부터 FAIL까지 모두를 가지고 있는게 아니에요

2018-11-14 14:43 UTC, huhsay commented on src/main/java/view/OutputView.java
> +    private static final int CORRECT_3NUMBERS_BENEFIT = 5000;
제 생각엔 Benefit은 model에 있는 것이 더 좋을 것 같은데, 한번더 생각해봐야 할 것 같습니다.

2018-11-14 14:43 UTC, huhsay commented on src/main/java/model/LottoList.java
> +
라인을 정리해주세요

2018-11-14 14:43 UTC, huhsay commented on src/main/java/LottoApplication.java
> +        winningChecker.checkWinningLotto(lottoListDTO.getLottoList(), InputView.inputWinningNumbers(), money);
money에 대한 정보는 lottoListDTO에 있으면 안되나요?

2018-11-14 14:43 UTC, huhsay commented on src/main/java/model/WinningInfo.java
> +    FAIL(0, 0);
winning info 이니까  2,1,0에 대한 정보를 없애고 매치되는 것이 없을때는 null을 주면 좋을 것 같숩네다.

2018-11-14 14:43 UTC, huhsay commented on src/main/java/dto/WinningCheckerDTO.java
> +    private int[] winningList;
rank enum을 만들었으니 rank 값을 가지고 있으면 더 좋지 않을까요?