[이상은]로또 1단계 구현완료
JNU-econovation/java-study-lotto pull request #18
Opened 2018-10-31 11:45 UTC by sangeuni

LottoGame - MV모델로 구현했습니다.

2018-10-31 12:08 UTC, hyukjin-lee requested changes
구현 잘 했습니다~ 작은 피드백 몇개 남겼으니 확인하세요 👍

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/view/ResultView.java
> +    }
너무 비효율적인 코딩

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/view/ResultView.java
> +            System.out.println(lotto.getLotto().get(i).getLottoNumber());
lottoDTO로 이름 짓는게 나중에 혼돈되지 않고 좋을 것 같아요

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/view/LottoGameMain.java
> +        ResultView.printLotto(lottoDTO);
윗줄 지우고 ResultView.printLotto(new LottoDTO(lottoList));
하는게 깔끔할듯

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/view/InputView.java
> +        return money;
return scanner.nextInt(); 로 줄여도 됌!

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/model/LottoGame.java
> +
불필요한 공백

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/model/LottoGame.java
> +    }
좀 더 보기 좋게 짤 수 있는 방법을 고민해보면 좋을 것 같음!

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/model/LottoGame.java
> +        int count = (int) lotto.stream().filter(winningNumbers::contains).count();
stream 사용 시도 good~ 👍

2018-10-31 12:08 UTC, hyukjin-lee commented on src/main/java/model/LottoGame.java
> +    private int[] prizeLottoList = new int[4];
필드값들이 너무 많습니다. 한 클래스가 여러가지 일을 하고있거나 하나의 필드로부터 파생될 수 있는 것들이 있는지 확인해보세요. 필드값은 적을수록 좋습니다. 메소드의 매개변수와 return을 잘 활용해보세요

2018-11-12 05:31 UTC, merged

2018-11-14 11:25 UTC, Bellroute commented on src/main/java/model/LottoGame.java
> +            lottoList.get(i).setNumber();
new Lotto().setNumber()로 하면 한 줄로 코딩 가능할 것 같습니다.